#!/usr/bin/env bash
# Installing Nginx on web-01

sudo apt-get -y update
sudo apt-get -y install update
sudo apt-get -y install nginx
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
sudo service nginx start
