#!/usr/bin/env bash
# using for loop with if else statement

for i in {1..10};
do
	if [ "$i" == 4 ]
	then
		echo "bad luck"
	elif [ "$i" == 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
done
