#!/usr/bin/env bash
# using for loop with if else statement

i=0
while [ $i -lt 10 ]
do
	((i++))
	if [ "$i" == 4 ]
	then
		echo "bad luck"
	elif [ "$i" == 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
done
