#!/usr/bin/env bash
# check file existance

FILENAME="school"
if [ -f "$FILENAME" ];
then
	echo "school file exists"

	if [ ! -s "$FILENAME" ];
	then
		echo "school file is empty"
	else
		echo "school file is not empty"
	fi

	if [ -f "$FILENAME" ];
	then
		echo "school is a regular file"
	fi

else
	echo "school file does not exist"
fi
