#!/usr/bin/env bash
# check file existance

FILEMANE="school"
if [ -f "$FILENAME" ];
then
	echo "school file exists"

	if [ ! -s "$FILENAME" ];
	then
		echo "school file is empty"
	else
		echo "school file is not empty"
	fi
	echo "school is a regular file"

	#if [ -f "$FILENAME" ];
	#then
	#	echo "school is a regular file"
	#fi

else
	echo "school file does not exist"
fi
